services:
  mysql:
    image: mysql:8.0
    container_name: library_mysql
    environment:
      MYSQL_DATABASE: library
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3345:3306"
    volumes:
      - mysql_data_jdbc:/var/lib/mysql
      - ./docker/mysql/init:/docker-entrypoint-initdb.d:ro
volumes:
  mysql_data_jdbc:
